### ISSUE TITLE
Incompatible with latest Zotero beta

### ISSUE THREAD

**Issue by champagnealexandre** [welpdx/zotero-citationcounts#2]
### **Describe the bug **
See title

**Desktop (please complete the following information):**
 - Add-on Version 1.3.0
 - Zotero Version 6.0-beta.4+a7cf689df
 - OS: macos monterey 12.2.1 (21D62)

**Screenshots**
<img width="713" alt="image" src="https://user-images.githubusercontent.com/30211986/156803784-1d649ee6-b9d6-471b-808e-7fed81caa24e.png">

**Additional Info**

**Comment by welpdx** [comment]
Thanks. Didn't see your issue until I used Zotero today. Imma get on it

**Comment by welpdx** [comment]
Please see [new release](https://github.com/welpdx/zotero-citationcounts/releases/tag/v1.3.1). Or update from the Zotero Add-ons Manager. 

Please make more issues please if you find any. I don't think there should be any as I haven't done much since last time. I'm kinda glad I didn't because I see how the scite team is having some issues with their columns with zotero v6.0. Btw is scite working for you?

Anyways, thanks again for the issue. Imma now go figure out why I don't get notifications github.

**Comment by champagnealexandre** [comment]
Just updated, seems to be working now thanks!

Scites also seems to be working but tbh I haven’t played much with Zotero plugins recently.

**Comment by welpdx** [comment]
Good to hear it is working!
Thanks again for making the issue and for your reply. I really appreciate it

**Comment by champagnealexandre** [comment]
hey no worries, I’m the one thanking you for the plugin :-)
